# Generated by Django 5.2.8 on 2025-12-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Özellik Adı')),
                ('slug', models.SlugField(unique=True)),
                ('input_type', models.CharField(choices=[('select', 'Seçmeli (Dropdown)'), ('number', 'Sayısal Değer (Elle Girilen)'), ('text', 'Serbest Metin')], default='select', max_length=10, verbose_name='Veri Tipi')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Birim')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('stock', models.IntegerField(default=0, verbose_name='Ürün Stok Sayısı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Kategori Adı')),
                ('is_active', models.BooleanField(default=True, help_text='İşaret kaldırılır ise kategori artık pasif hale gelir.', verbose_name='Kategori Durumu (Aktif veya Pasif)')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Bu kategori, bir üst kategoriye sahipse lütfen seçiniz.', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Değer')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Product.feature')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_custom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manuel Değer')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Product.product')),
                ('value_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.featurevalue', verbose_name='Seçilen Değer')),
            ],
            options={
                'verbose_name': 'Ürün Özelliği',
                'verbose_name_plural': 'Ürün Özellikleri',
                'unique_together': {('product', 'feature')},
            },
        ),
    ]
