# Generated by Django 5.2.8 on 2025-12-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='slug',
        ),
    ]
